### ISSUE TITLE
How to generate an image with both numbers and English letters?

### ISSUE THREAD

**Issue by xiaotongtong9293** [Belval/TextRecognitionDataGenerator#61]
How can I generate a picture with more numbers from 0-9 or generate an image with both numbers and English letters?

**Comment by Belval** [comment]
To generate a picture with numbers only:

`python3 run.py -c 1 -rs -num`

![5655034_0](https://user-images.githubusercontent.com/5399488/58051787-1e0fcd00-7b21-11e9-8d7b-954ff10ca301.jpg)

The number is random, I think I'll had a parameter for it.

To generate a picture with numbers and letters:

`python3 run.py -c 1 -rs -num -let`

![fDKX5m_0](https://user-images.githubusercontent.com/5399488/58051853-4a2b4e00-7b21-11e9-87d3-63d2671bbc1a.jpg)
![GnDW9KPQf_0](https://user-images.githubusercontent.com/5399488/58051854-4ac3e480-7b21-11e9-8c31-9d314c19f9dd.jpg)
![pSpolOPP_0](https://user-images.githubusercontent.com/5399488/58051855-4ac3e480-7b21-11e9-8683-f109dae58698.jpg)

Again, length is random, so that's a bit disappointing. You can get longer images by using `-w` but that will add spaces between each group.

`python3 run.py -c 1 -rs -num -let -w 5`

![ixolJ0 xZTQAgol2A kG WMvsN Y8Slu_0](https://user-images.githubusercontent.com/5399488/58051930-721ab180-7b21-11e9-86f8-bd17711fc313.jpg)
![uLUl4rHgpT wiTZz N0HUa 9p6mfL E075jp_0](https://user-images.githubusercontent.com/5399488/58051931-721ab180-7b21-11e9-8f9a-827b4e8a2a2c.jpg)

**Comment by xiaotongtong9293** [comment]
@Belval That's nice! Thank you so much!  How can the generated picture size be set to the same?
Can I set the size of the generated picture myself?

**Comment by xiaotongtong9293** [comment]
That's so nice! Thank you !
